volumes:
  wordpress:
    driver: local
    name: wordpress-volume
    driver_opts:
      device: ~/data/wordpress-volume
      o: bind
      type: none

  mariadb:
    driver: local
    name: mariadb-volume
    driver_opts:
      device: ~/data/mariadb-volume
      o: bind
      type: none

networks:
  inception:
    driver: bridge
    name: inception

services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx/.
    image: nginx:42
    ports:
     - "443:443"
    depends_on:
      - wordpress
    volumes:
     - wordpress:/var/www/html
    networks:
      - inception
    env_file:
      - .env
    restart: on-failure

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress/.
    image: wordpress:42
    expose:
      - "9000"
    depends_on:
      - mariadb
      - redis
    volumes:
      - wordpress:/var/www/html
    env_file:
      - .env
    networks:
      - inception
    restart: on-failure
 
  mariadb:
    container_name: mariadb
    expose:
      - "3306"
    build: ./requirements/mariadb/.
    image: mariadb:42
    volumes:
      - mariadb:/var/lib/mysql
    env_file:
      - .env
    networks:
      - inception
    restart: on-failure

  # BONUS SERVICES ----------------------------------------------

  # Redis caches data and reduces the number of database queries
  redis:
    container_name: redis
    build: requirements/bonus/redis
    image: redis:42
    expose:
      - "6379"
    networks:
      - inception
    restart: on-failure
  
  # FTP server for modificating the wordpress website files
  ftp-server:
    container_name: ftp-server
    build: requirements/bonus/ftp
    image: ftp:42
    ports:
      - "21:21" # FTP control port for command connections
      - "21100-21110:21100-21110"  # FTP passive ports for data connections
    volumes:
      - wordpress:/var/www/html
    env_file:
      - .env
    networks:
      - inception
    restart: on-failure

  # Adminer webui for managing db, works top of mariadb
  adminer:
    container_name: adminer
    build: requirements/bonus/adminer
    image: adminer:42
    expose:
      - "8080"
    networks:
      - inception
    restart: on-failure
